# Fraudulent Listing Detection
This notebook builds a machine learning model to identify fraudulent online product listings.

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

# Load the Dataset
This step loads the dataset into a pandas DataFrame.

In [2]:
df = pd.read_csv("../data/fraud-detection-ecommerce.csv.")

# View the First Five Rows
This step displays the first five rows of the dataset.

In [3]:
df.head()

,transaction_id,user_id,account_age_days,total_transactions_user,avg_amount_user,amount,country,bin_country,channel,merchant_category,promo_used,avs_match,cvv_result,three_ds_flag,transaction_time,shipping_distance_km,is_fraud
0,1,1,141,47,147.93,84.75,FR,FR,web,travel,0,1,1,1,2024-01-06T04:09:39Z,370.95,0
1,2,1,141,47,147.93,107.90,FR,FR,web,travel,0,0,0,0,2024-01-09T20:13:47Z,149.62,0
2,3,1,141,47,147.93,92.36,FR,FR,app,travel,1,1,1,1,2024-01-12T06:20:11Z,164.08,0
3,4,1,141,47,147.93,112.47,FR,FR,web,fashion,0,1,1,1,2024-01-15T17:00:04Z,397.40,0
4,5,1,141,47,147.93,132.91,FR,US,web,electronics,0,1,1,1,2024-01-17T01:27:31Z,935.28,0

# Dataset Dimesions
This step displays the number of rows and columns in the dataset.

In [4]:
df.shape

(299695, 17)

# Display Dataset Information
This step shows the dataset structure, data types, and missing values.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299695 entries, 0 to 299694
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   transaction_id           299695 non-null  int64
 1   user_id                  299695 non-null  int64
 2   account_age_days         299695 non-null  int64
 3   total_transactions_user  299695 non-null  int64
 4   avg_amount_user          299695 non-null  float64
 5   amount                   299695 non-null  float64
 6   country                  299695 non-null  object
 7   bin_country              299695 non-null  object
 8   channel                  299695 non-null  object
 9   merchant_category        299695 non-null  object
 10  promo_used               299695 non-null  int64
 11  avs_match                299695 non-null  int64
 12  cvv_result               299695 non-null  int64
 13  three_ds_flag            299695 non-null  int64
 14  transaction_time         299695 non-null  object
 15  shipping_distance_km     299695 non-null  float64
 16  is_fraud                 299695 non-null  int64
dtypes: float64(3), int64(9), object(5)
memory usage: 38.9+ MB

# Check Missing Values
This step displays the number of missing values in each columns.

In [6]:
df.isnull().sum()

transaction_id             0
user_id                    0
account_age_days           0
total_transactions_user    0
avg_amount_user            0
amount                     0
country                    0
bin_country                0
channel                    0
merchant_category          0
promo_used                 0
avs_match                  0
cvv_result                 0
three_ds_flag              0
transaction_time           0
shipping_distance_km       0
is_fraud                   0
dtype: int64

# Display Column Names
This step lists all the columns in the dataset.

In [7]:
df.columns

Index(['transaction_id', 'user_id', 'account_age_days',
       'total_transactions_user', 'avg_amount_user', 'amount', 'country',
       'bin_country', 'channel', 'merchant_category', 'promo_used',
       'avs_match', 'cvv_result', 'three_ds_flag', 'transaction_time',
       'shipping_distance_km', 'is_fraud'],
      dtype='object')

# Display Summary Statistics
This step displays summary statistics for the numerical columns.

In [8]:
df.describe()

,transaction_id,user_id,account_age_days,total_transactions_user,avg_amount_user,amount,promo_used,avs_match,cvv_result,three_ds_flag,shipping_distance_km,is_fraud
count,299695.0000,299695.000000,299695.000000,299695.000000,299695.000000,299695.000000,299695.000000,299695.000000,299695.000000,299695.000000,299695.000000,299695.000000
mean,149848.0000,3002.559432,973.397871,50.673321,148.142973,177.165279,0.153640,0.837999,0.872110,0.784588,357.049028,0.022062
std,86514.6388,1732.309663,525.241409,5.976391,200.364624,306.926507,0.360603,0.368453,0.333968,0.411109,427.672074,0.146887
min,1.0000,1.000000,1.000000,40.000000,3.520000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,74924.5000,1501.000000,516.000000,46.000000,46.190000,42.100000,0.000000,1.000000,1.000000,1.000000,136.600000,0.000000
50%,149848.0000,3007.000000,975.000000,51.000000,90.130000,89.990000,0.000000,1.000000,1.000000,1.000000,273.020000,0.000000
75%,224771.5000,4504.000000,1425.000000,56.000000,173.450000,191.110000,0.000000,1.000000,1.000000,1.000000,409.180000,0.000000
max,299695.0000,6000.000000,1890.000000,60.000000,4565.290000,16994.740000,1.000000,1.000000,1.000000,1.000000,3748.560000,1.000000

# Display First 10 Rows
This step displays the first ten rows for a better understanding of the dataset.

In [9]:
df.head(10)

,transaction_id,user_id,account_age_days,total_transactions_user,avg_amount_user,amount,country,bin_country,channel,merchant_category,promo_used,avs_match,cvv_result,three_ds_flag,transaction_time,shipping_distance_km,is_fraud
0,1,1,141,47,147.93,84.75,FR,FR,web,travel,0,1,1,1,2024-01-06T04:09:39Z,370.95,0
1,2,1,141,47,147.93,107.90,FR,FR,web,travel,0,0,0,0,2024-01-09T20:13:47Z,149.62,0
2,3,1,141,47,147.93,92.36,FR,FR,app,travel,1,1,1,1,2024-01-12T06:20:11Z,164.08,0
3,4,1,141,47,147.93,112.47,FR,FR,web,fashion,0,1,1,1,2024-01-15T17:00:04Z,397.40,0
4,5,1,141,47,147.93,132.91,FR,US,web,electronics,0,1,1,1,2024-01-17T01:27:31Z,935.28,0
5,6,1,141,47,147.93,224.82,FR,FR,web,travel,0,1,1,1,2024-01-26T22:05:08Z,289.06,0
6,7,1,141,47,147.93,125.98,FR,FR,app,electronics,0,1,1,1,2024-01-30T00:51:41Z,443.75,0
7,8,1,141,47,147.93,66.95,FR,RO,web,travel,0,1,1,1,2024-02-11T15:33:30Z,1390.59,0
8,9,1,141,47,147.93,261.58,FR,FR,app,grocery,0,0,0,0,2024-02-22T01:29:55Z,110.51,0
9,10,1,141,47,147.93,97.34,FR,FR,web,electronics,0,0,1,1,2024-03-09T11:13:19Z,232.34,0

# Check Class Distribution
This step checks the distribution of fraudulent and genuine listings.

In [10]:
df.iloc[:, -1].value_counts()

is_fraud
0    293083
1      6612
Name: count, dtype: int64

# Separate Features and Target
This step separates the input features and the target variable.

In [11]:
X = df.drop("is_fraud", axis=1)
y = df["is_fraud"]

# Check Feature Data Types
This step displays the data types of the input features.

In [12]:
X.dtypes

transaction_id               int64
user_id                      int64
account_age_days             int64
total_transactions_user      int64
avg_amount_user            float64
amount                     float64
country                     object
bin_country                 object
channel                     object
merchant_category           object
promo_used                   int64
avs_match                    int64
cvv_result                   int64
three_ds_flag                int64
transaction_time            object
shipping_distance_km       float64
dtype: object

# Convert Categorical Features
This step converts categorical features into numerical form using one-hot encoding.

In [13]:
X = pd.get_dummies(
    X,
    columns=["country", "bin_country", "channel", "merchant_category"],
    drop_first=True
)

# Convert Transaction Time
This step converts the transaction time columns into datetime format.

In [15]:
X["transaction_time"] = pd.to_datetime(X["transaction_time"])

# Extract Date-Time Features
This step extracts useful features from the transaction time.

In [16]:
X["hour"] = X["transaction_time"].dt.hour
X["day"] = X["transaction_time"].dt.day
X["month"] = X ["transaction_time"].dt.month

X = X.drop("transaction_time", axis=1)

# Split the Dataset
This step splits the data into training and testing sets.

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Train a Random Forest Classifier
This step trains a Random Forest model to detect fraudulent listings.

In [18]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

# Predict Fraudulent Listings
This step predicts whether the listings in the test set are fraudulent or genuine.

In [19]:
y_pred = model.predict(X_test)

# Evaluate Model Accuracy
This step calculates the accuracy of the trained model.

In [21]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.992142011044562

# Display Clasiification Report
This step displays precision, recall, F1-score, and support for each other.

In [22]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00     58617
           1       0.94      0.69      0.79      1322

    accuracy                           0.99     59939
   macro avg       0.96      0.84      0.90     59939
weighted avg       0.99      0.99      0.99     59939

# Display Confusion Matrix
This step displays the confusion matrix of the model predictions.

In [23]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[58555,    62],
       [  409,   913]])

# Save Predictions
This step saves the model predictions to a CSV file.

In [27]:
predictions = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})

predictions.to_csv("../models/fraud-predictions.csv", index=False)

# Project Summary

This project built a Random Forest classifier to detect fraudulent online listings. The data was preprocessed, categorical features were encoded, date-time features were extracted, and the model was evaluated using accuracy, a classification report, and a confusion matrix.